# Generated by Django 3.2.20 on 2023-08-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_recipes', '0002_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='min_hour',
            field=models.IntegerField(choices=[(0, 'Min'), (1, 'Hour')], default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
