# Generated by Django 3.2.20 on 2023-08-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_recipes', '0003_auto_20230829_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='min_hour',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(max_length=100),
        ),
    ]
