# Generated by Django 3.2.20 on 2023-08-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_recipes', '0006_auto_20230829_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cook_prepare_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
