# Generated by Django 3.2.20 on 2023-08-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_recipes', '0007_auto_20230829_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(max_length=20),
        ),
    ]
