# Generated by Django 3.2.20 on 2023-08-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_recipes', '0009_alter_recipe_cook_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cook_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_cook_time',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
