# Generated by Django 3.2.20 on 2023-08-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_recipes', '0010_auto_20230829_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='prep_cook_time',
        ),
    ]
