# Generated by Django 3.2.20 on 2023-08-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_recipes', '0011_remove_recipe_prep_cook_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
