# Generated by Django 3.2.20 on 2023-08-31 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_recipes', '0014_alter_recipe_min_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
    ]
